# Generated by Django 4.2.16 on 2026-06-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0008_alter_house_options_remove_house_floor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee_month", models.CharField(max_length=20, verbose_name="账单月份")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("unpaid", "未缴费"), ("paid", "已缴费")],
                        default="unpaid",
                        max_length=20,
                        verbose_name="缴费状态",
                    ),
                ),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="缴费时间"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="community.house",
                        verbose_name="所属房屋",
                    ),
                ),
            ],
            options={
                "db_table": "fee",
            },
        ),
    ]
