# Generated by Django 4.2.16 on 2026-06-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owners", "0008_owner_status"),
        ("community", "0009_house_unique_room_per_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("property", "物业费"),
                            ("water", "水费"),
                            ("electric", "电费"),
                            ("parking", "停车费"),
                            ("other", "其他费用"),
                        ],
                        max_length=30,
                        verbose_name="费用类型",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金额"
                    ),
                ),
                ("deadline", models.DateTimeField(verbose_name="缴费截止日期")),
                (
                    "pay_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="缴费时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未缴费"),
                            ("paid", "已缴费"),
                            ("overdue", "已逾期"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("remark", models.TextField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.house",
                        verbose_name="房屋",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="owners.owner",
                        verbose_name="业主",
                    ),
                ),
            ],
            options={
                "db_table": "fee",
            },
        ),
    ]
