# Generated by Django 4.2.16 on 2026-06-03 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_alter_house_options_remove_house_floor_and_more"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("property", "物业费"),
                    ("parking", "车位费"),
                    ("water", "水费"),
                    ("electric", "电费"),
                ],
                default="property",
                max_length=30,
                verbose_name="费用类型",
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="金额"
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="community.house",
                verbose_name="房屋",
            ),
        ),
        migrations.AlterField(
            model_name="fee",
            name="pay_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fee",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fee",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "未缴费"), ("paid", "已缴费")],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
