# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fee",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alipay", "支付宝"),
                    ("wechat", "微信"),
                    ("bank_card", "银行卡"),
                    ("apple_pay", "Apple Pay"),
                    ("union_pay", "云闪付"),
                ],
                max_length=30,
                null=True,
                verbose_name="支付方式",
            ),
        ),
    ]
