# Generated by Django 4.2.16 on 2026-05-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0008_alter_house_options_remove_house_floor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parking_no",
                    models.CharField(max_length=50, verbose_name="车位编号"),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="面积"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="idle", max_length=20, verbose_name="状态"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parkings",
                        to="community.house",
                        verbose_name="所属房屋",
                    ),
                ),
            ],
            options={
                "db_table": "parking",
            },
        ),
    ]
