# Generated by Django 4.2.16 on 2026-05-14 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=16, unique=True, verbose_name='车牌号')),
                ('car_brand', models.CharField(blank=True, max_length=32, null=True, verbose_name='车辆品牌')),
                ('car_model', models.CharField(blank=True, max_length=32, null=True, verbose_name='车型')),
                ('parking_no', models.CharField(max_length=32, verbose_name='车位号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner', verbose_name='所属业主')),
            ],
            options={
                'verbose_name': '车位',
                'verbose_name_plural': '车位',
                'db_table': 'parking',
            },
        ),
    ]
