# Generated by Django 4.2.16 on 2026-06-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0004_owner_relationship"),
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parking",
            name="house",
        ),
        migrations.AddField(
            model_name="parking",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parkings",
                to="owners.owner",
                verbose_name="所属业主",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parking",
            name="parking_no",
            field=models.CharField(max_length=50, unique=True, verbose_name="车位号"),
        ),
        migrations.AlterField(
            model_name="parking",
            name="status",
            field=models.CharField(
                choices=[("idle", "空闲"), ("used", "使用中")],
                default="used",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
