# Generated by Codex on 2026-06-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0008_owner_status"),
        ("parking", "0002_remove_parking_house_parking_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parkings",
                to="owners.owner",
                verbose_name="所属业主",
            ),
        ),
    ]
