# Generated by Django 4.2.16 on 2026-06-12 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owners', '0008_owner_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('complaint', '投诉'), ('suggestion', '建议')], default='complaint', max_length=20, verbose_name='类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('handle_result', models.TextField(blank=True, default='', verbose_name='处理结果')),
                ('return_visit', models.TextField(blank=True, default='', verbose_name='回访记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='owners.owner', verbose_name='业主')),
            ],
            options={
                'verbose_name': '投诉建议',
                'verbose_name_plural': '投诉建议',
                'db_table': 'complaint',
                'ordering': ['-id'],
            },
        ),
    ]
