# Generated by Django 4.2.16 on 2026-06-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owners", "0006_owner_avatar"),
        ("parking", "0002_remove_parking_house_parking_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_no", models.CharField(max_length=20, verbose_name="车牌号")),
                ("brand", models.CharField(max_length=50, verbose_name="车辆品牌")),
                ("color", models.CharField(max_length=20, verbose_name="车辆颜色")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="owners.owner",
                        verbose_name="所属业主",
                    ),
                ),
                (
                    "parking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parking.parking",
                        verbose_name="绑定车位",
                    ),
                ),
            ],
            options={
                "verbose_name": "车辆",
                "verbose_name_plural": "车辆",
                "db_table": "car",
            },
        ),
    ]
