# Generated by Django 4.2.16 on 2026-06-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "车辆管理", "verbose_name_plural": "车辆管理"},
        ),
        migrations.AddField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[("monthly", "月租车"), ("temporary", "临时车")],
                default="monthly",
                max_length=20,
                verbose_name="车辆类型",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="plate_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="车牌号"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="颜色"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="车辆颜色"
            ),
        ),
    ]
