# Generated by Django 4.2.16 on 2026-06-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_alter_car_options_car_car_type_car_plate_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[("normal", "正常"), ("disabled", "禁用")],
                default="normal",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
