# Generated by Django 4.2.16 on 2026-06-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_car_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="plate_number",
        ),
    ]
