# Generated by Django 4.2.16 on 2026-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_remove_car_plate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="plate_no",
            field=models.CharField(max_length=20, unique=True, verbose_name="车牌号"),
        ),
    ]
