# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("general", "系统公告"),
                    ("activity", "活动通知"),
                    ("finance", "财务公告"),
                    ("repair", "维修公告"),
                ],
                default="general",
                max_length=20,
                verbose_name="公告类型",
            ),
        ),
    ]
