# Generated by Django 4.2.16 on 2026-05-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, to="users.permission", verbose_name="角色权限"
            ),
        ),
    ]
