# Generated by Django 4.2.16 on 2026-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="手机号"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="real_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="真实姓名"
            ),
        ),
    ]
