# Generated by Django 4.2.16 on 2026-05-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, max_length=128, null=True, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, max_length=128, null=True, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='图标')),
                ('sort', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.menu')),
            ],
            options={
                'db_table': 'sys_menu',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.menu'),
        ),
    ]
