# Generated by Django 4.2.16 on 2026-05-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_phone_alter_user_real_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.menu",
                verbose_name="菜单",
            ),
        ),
    ]
