# Generated by Django 4.2.16 on 2026-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_menu_permission_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.RemoveField(
            model_name='permission',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='name',
        ),
        migrations.AddField(
            model_name='permission',
            name='method',
            field=models.CharField(default='GET', max_length=20),
        ),
        migrations.AddField(
            model_name='permission',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='title',
            field=models.CharField(default='system', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='permission',
            table='permission',
        ),
    ]
