# Generated by Django 4.2.16 on 2026-06-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_permission_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="roles",
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_type",
            field=models.IntegerField(default=1, verbose_name="菜单类型"),
        ),
    ]
