# Generated by Django 4.2.16 on 2026-06-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_menu_roles_menu_menu_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "角色", "verbose_name_plural": "角色"},
        ),
        migrations.AlterField(
            model_name="permission",
            name="code",
            field=models.CharField(max_length=100, unique=True, verbose_name="权限编码"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                to="users.permission",
                verbose_name="权限",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_users",
                to="users.role",
                verbose_name="主角色",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "正常"), (0, "禁用")],
                default=1,
                verbose_name="账号状态",
            ),
        ),
        migrations.AlterModelTable(
            name="role",
            table="users_role",
        ),
    ]
