# Generated by Django 4.2.16 on 2026-05-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_permission_options_remove_permission_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default='默认角色', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
    ]
