# Generated by Django 4.2.16 on 2026-05-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_role_code_remove_role_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='hidden',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否隐藏'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='菜单名称'),
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, to='users.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='前端组件'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.menu', verbose_name='父菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
    ]
