# 文件说明：维护 Django 项目配置，包括应用、中间件、数据库、JWT 和缓存。

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path

from django.core.management.utils import get_random_secret_key

# 项目路径分块：所有相对路径都基于 BASE_DIR 派生。
BASE_DIR = Path(__file__).resolve().parent.parent


# 环境变量读取分块：先读取 .env，再让系统环境变量保持最高优先级。
def load_env_file(path):
    """轻量读取本地 .env，避免开发命令漏配环境变量；已有环境变量优先。"""

    if not path.exists():
        return

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()

        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")

        if key and key not in os.environ:
            os.environ[key] = value


load_env_file(BASE_DIR / ".env")


# 环境变量解析工具分块：集中处理布尔值和逗号列表，避免各处重复解析。
def env_bool(name, default=False):
    """把环境变量里的布尔字符串转换为 Python bool。"""

    value = os.environ.get(name)

    if value is None:
        return default

    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=None):
    """读取逗号分隔的环境变量列表，避免把域名和 CORS 来源写死在代码中。"""

    value = os.environ.get(name)

    if not value:
        return default or []

    return [item.strip() for item in value.split(",") if item.strip()]


# 基础安全配置分块：生产默认关闭 DEBUG，并要求关键密钥显式配置。
# Quick-start development settings - unsuitable for production unless env is set
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# DEBUG 默认关闭，开发环境可显式设置 DJANGO_DEBUG=true。
DEBUG = env_bool("DJANGO_DEBUG", default=False)
IS_TESTING = "test" in sys.argv

# 非调试环境必须显式提供长期密钥，避免进程重启后生成临时密钥导致 token/session 全部失效。
raw_secret_key = os.environ.get("DJANGO_SECRET_KEY")

if not DEBUG and not IS_TESTING and not raw_secret_key:
    raise RuntimeError("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=false")

if (
    not DEBUG
    and not IS_TESTING
    and raw_secret_key
    and (
        raw_secret_key == "replace-with-a-long-random-local-secret"
        or len(raw_secret_key) < 50
    )
):
    raise RuntimeError("DJANGO_SECRET_KEY is too weak for production")

SECRET_KEY = raw_secret_key or get_random_secret_key()

# 允许的主机由环境变量控制，默认只放开本机和测试客户端。
ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost", "testserver"],
)

# 媒体文件分块：上传文件保存目录和外部访问前缀。

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = "/media/"


# 应用注册分块：业务模块、DRF、JWT 黑名单和跨域组件在这里统一启用。
# Application definition

INSTALLED_APPS = [
    # django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.users",
    "apps.community",
    "apps.owners",
    "apps.parking",
    "apps.cars",
    "apps.finance",
    "apps.notice",
    "apps.repairs",
    "apps.dashboard",
    "apps.logs",
    "apps.upload",
    "apps.visitors",
    "apps.complaints",
    "apps.chat",
    "django_extensions",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# 接口安全分块：跨域和 DRF 默认认证策略统一配置。
# CORS 默认不再放开所有来源；开发调试时可设置 DJANGO_CORS_ALLOW_ALL_ORIGINS=true。
CORS_ALLOW_ALL_ORIGINS = env_bool("DJANGO_CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = env_list(
    "DJANGO_CORS_ALLOWED_ORIGINS",
    default=[
        "http://127.0.0.1:5173",
        "http://localhost:5173",
    ],
)

if not DEBUG and not IS_TESTING and CORS_ALLOW_ALL_ORIGINS:
    raise RuntimeError("DJANGO_CORS_ALLOW_ALL_ORIGINS cannot be true in production")

REST_FRAMEWORK = {
    # JWT 认证
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # 默认接口需要登录；登录、注册、验证码等公开接口在对应 View 里显式放行。
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "property-management-auth-cache",
    }
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# 数据库配置分块：测试缺少 MySQL 密码时走内存 SQLite，避免默认测试漏跑。
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if IS_TESTING and not os.environ.get("MYSQL_PASSWORD"):
    # 默认测试命令不依赖本机 MySQL 密码，避免 manage.py test 因环境变量缺失而漏跑。
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    if not DEBUG and not IS_TESTING:
        required_db_envs = ("MYSQL_DATABASE", "MYSQL_USER", "MYSQL_PASSWORD")
        missing_db_envs = [name for name in required_db_envs if not os.environ.get(name)]

        if missing_db_envs:
            raise RuntimeError(
                "Missing required database environment variables: "
                + ", ".join(missing_db_envs)
            )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.environ.get("MYSQL_DATABASE", "property_management"),
            "USER": os.environ.get("MYSQL_USER", "root"),
            "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
            "HOST": os.environ.get("MYSQL_HOST", "127.0.0.1"),
            "PORT": os.environ.get("MYSQL_PORT", "3306"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "users.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# JWT 分块：refresh token 依赖 token_blacklist 应用，退出登录会把 refresh 加入黑名单。
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 生产安全分块：开发和测试环境允许本地 HTTP，生产环境强制 HTTPS 跳转。
secure_default = not DEBUG and not IS_TESTING
SECURE_SSL_REDIRECT = (
    env_bool("DJANGO_SECURE_SSL_REDIRECT", default=secure_default)
)
SECURE_HSTS_SECONDS = int(
    os.environ.get("DJANGO_SECURE_HSTS_SECONDS", 31536000 if secure_default else 0)
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=secure_default,
)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=secure_default)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=secure_default)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=secure_default)
SESSION_COOKIE_SAMESITE = os.environ.get("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE = os.environ.get("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get(
    "DJANGO_SECURE_REFERRER_POLICY",
    "same-origin",
)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
X_FRAME_OPTIONS = "DENY"

# 认证与上传安全阈值分块：登录限流、调试短信和上传白名单都由环境变量覆盖。
LOGIN_FAIL_LIMIT = int(os.environ.get("LOGIN_FAIL_LIMIT", 5))
LOGIN_FAIL_WINDOW_SECONDS = int(os.environ.get("LOGIN_FAIL_WINDOW_SECONDS", 600))
LOGIN_LOCK_SECONDS = int(os.environ.get("LOGIN_LOCK_SECONDS", 900))
AUTH_RETURN_DEBUG_SMS_CODE = env_bool("AUTH_RETURN_DEBUG_SMS_CODE", default=False)
UPLOAD_MAX_SIZE = int(os.environ.get("UPLOAD_MAX_SIZE", 10 * 1024 * 1024))
UPLOAD_ALLOWED_FILE_EXTS = env_list(
    "UPLOAD_ALLOWED_FILE_EXTS",
    default=[
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".webp",
        ".pdf",
        ".doc",
        ".docx",
        ".xls",
        ".xlsx",
        ".txt",
        ".csv",
        ".zip",
    ],
)
