# Generated by Django 4.2.16 on 2026-06-05 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("owners", "0006_owner_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="访客姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="手机号")),
                (
                    "id_card",
                    models.CharField(
                        blank=True, max_length=18, null=True, verbose_name="身份证"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="来访事由"
                    ),
                ),
                ("visit_time", models.DateTimeField(verbose_name="来访时间")),
                (
                    "leave_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="离开时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "待到访"),
                            ("entered", "已到访"),
                            ("left", "已离开"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="owners.owner",
                        verbose_name="被访业主",
                    ),
                ),
            ],
            options={
                "verbose_name": "访客",
                "verbose_name_plural": "访客",
                "db_table": "visitor",
            },
        ),
    ]
