# Generated by Django 4.2.16 on 2026-06-09 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("visitors", "0002_visitor_approve_remark_visitor_approve_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="enter_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="到访时间"),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="approve_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "待审批"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                    ("entered", "已到访"),
                    ("left", "已离开"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
