# Generated by Django 4.2.16 on 2026-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0003_visitor_enter_time_alter_visitor_approve_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="phone",
            field=models.CharField(db_index=True, max_length=20, verbose_name="手机号"),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                    ("entered", "已到访"),
                    ("left", "已离开"),
                ],
                default="waiting",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
