# Generated by Django 4.2.16 on 2026-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="用户名")),
                ("ip", models.CharField(max_length=100, verbose_name="IP地址")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
            ],
            options={
                "db_table": "login_log",
            },
        ),
    ]
