# Generated by Django 4.2.16 on 2026-05-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='小区名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='小区编码')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, max_length=32, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'community',
            },
        ),
    ]
