# Generated by Django 4.2.16 on 2026-05-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='楼栋名称')),
                ('code', models.CharField(max_length=32, verbose_name='楼栋编码')),
                ('floor_count', models.IntegerField(default=1, verbose_name='楼层数')),
                ('unit_count', models.IntegerField(default=1, verbose_name='单元数')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community', verbose_name='所属小区')),
            ],
            options={
                'verbose_name': '楼栋',
                'verbose_name_plural': '楼栋',
                'db_table': 'building',
            },
        ),
    ]
