# Generated by Django 4.2.16 on 2026-05-14 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_building'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': '小区', 'verbose_name_plural': '小区'},
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='单元名称')),
                ('code', models.CharField(max_length=32, verbose_name='单元编码')),
                ('floor_count', models.IntegerField(default=1, verbose_name='楼层数')),
                ('house_count', models.IntegerField(default=1, verbose_name='房屋数量')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.building', verbose_name='所属楼栋')),
            ],
            options={
                'verbose_name': '单元',
                'verbose_name_plural': '单元',
                'db_table': 'unit',
            },
        ),
    ]
