# Generated by Django 4.2.16 on 2026-05-14 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_options_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=32, verbose_name='房号')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='建筑面积')),
                ('inner_area', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='套内面积')),
                ('house_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='户型')),
                ('usage', models.CharField(default='住宅', max_length=32, verbose_name='用途')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.unit', verbose_name='所属单元')),
            ],
            options={
                'verbose_name': '房屋',
                'verbose_name_plural': '房屋',
                'db_table': 'house',
            },
        ),
    ]
