# Generated by Django 4.2.16 on 2026-05-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_house"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="community",
            name="status",
        ),
        migrations.AddField(
            model_name="community",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="联系人"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="community",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="小区地址"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="小区编码"),
        ),
        migrations.AlterField(
            model_name="community",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系电话"
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="小区名称"
            ),
        ),
    ]
