# Generated by Django 4.2.16 on 2026-05-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0005_remove_community_contact_person_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="building",
            options={},
        ),
        migrations.RemoveField(
            model_name="building",
            name="status",
        ),
        migrations.AlterField(
            model_name="building",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="楼栋编码"),
        ),
        migrations.AlterField(
            model_name="building",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buildings",
                to="community.community",
                verbose_name="所属小区",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="floor_count",
            field=models.IntegerField(default=0, verbose_name="总楼层"),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=50, verbose_name="楼栋名称"),
        ),
        migrations.AlterField(
            model_name="building",
            name="unit_count",
            field=models.IntegerField(default=0, verbose_name="单元数"),
        ),
    ]
