# Generated by Django 4.2.16 on 2026-05-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_alter_building_options_remove_building_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={},
        ),
        migrations.RemoveField(
            model_name="unit",
            name="house_count",
        ),
        migrations.RemoveField(
            model_name="unit",
            name="status",
        ),
        migrations.AlterField(
            model_name="unit",
            name="building",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="community.building",
                verbose_name="所属楼栋",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="单元编码"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="floor_count",
            field=models.IntegerField(default=0, verbose_name="楼层数"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=50, verbose_name="单元名称"),
        ),
    ]
