# Generated by Django 4.2.16 on 2026-05-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_alter_unit_options_remove_unit_house_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="house",
            options={},
        ),
        migrations.RemoveField(
            model_name="house",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="house",
            name="house_no",
        ),
        migrations.RemoveField(
            model_name="house",
            name="inner_area",
        ),
        migrations.RemoveField(
            model_name="house",
            name="usage",
        ),
        migrations.AddField(
            model_name="house",
            name="owner_count",
            field=models.IntegerField(default=0, verbose_name="业主数量"),
        ),
        migrations.AddField(
            model_name="house",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
        migrations.AddField(
            model_name="house",
            name="resident_count",
            field=models.IntegerField(default=0, verbose_name="居住人数"),
        ),
        migrations.AddField(
            model_name="house",
            name="room_no",
            field=models.CharField(default=101, max_length=20, verbose_name="房号"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="house",
            name="house_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="户型"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="status",
            field=models.CharField(
                choices=[
                    ("vacant", "空置"),
                    ("occupied", "已入住"),
                    ("renting", "出租"),
                    ("repairing", "装修中"),
                ],
                default="vacant",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="community.unit",
                verbose_name="所属单元",
            ),
        ),
    ]
