# Generated by Django 4.2.16 on 2026-06-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_alter_house_options_remove_house_floor_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="house",
            constraint=models.UniqueConstraint(
                fields=("unit", "room_no"), name="unique_room_per_unit"
            ),
        ),
    ]
