# Generated by Django 4.2.16 on 2026-05-14 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0004_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='业主姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('gender', models.SmallIntegerField(default=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系地址')),
                ('emergency_contact', models.CharField(blank=True, max_length=32, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='紧急联系电话')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.house', verbose_name='所属房屋')),
            ],
            options={
                'verbose_name': '业主',
                'verbose_name_plural': '业主',
                'db_table': 'owner',
            },
        ),
    ]
