# Generated by Django 4.2.16 on 2026-05-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_alter_house_options_remove_house_floor_and_more"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="owner",
            options={},
        ),
        migrations.RemoveField(
            model_name="owner",
            name="address",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="status",
        ),
        migrations.AddField(
            model_name="owner",
            name="move_in_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="owner",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="owner",
            name="gender",
            field=models.CharField(
                choices=[("male", "男"), ("female", "女")],
                default="male",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="community.house",
                verbose_name="房屋",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="name",
            field=models.CharField(max_length=50, verbose_name="姓名"),
        ),
    ]
