# Generated by Django 4.2.16 on 2026-06-01 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0008_alter_house_options_remove_house_floor_and_more"),
        ("owners", "0002_alter_owner_options_remove_owner_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="move_in_date",
        ),
        migrations.AddField(
            model_name="owner",
            name="birthday",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AddField(
            model_name="owner",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="是否主业主"),
        ),
        migrations.AlterField(
            model_name="owner",
            name="gender",
            field=models.CharField(
                choices=[("male", "男"), ("female", "女")],
                default="male",
                max_length=10,
                verbose_name="性别",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="community.house",
                verbose_name="所属房屋",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="phone",
            field=models.CharField(max_length=20, unique=True, verbose_name="手机号"),
        ),
        migrations.AlterField(
            model_name="owner",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
