# Generated by Django 4.2.16 on 2026-06-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0003_remove_owner_move_in_date_owner_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("self", "本人"),
                    ("spouse", "配偶"),
                    ("child", "子女"),
                    ("parent", "父母"),
                    ("other", "其他"),
                ],
                default="self",
                max_length=20,
                verbose_name="与主业主关系",
            ),
        ),
    ]
