# Generated by Django 4.2.16 on 2026-06-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0004_owner_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="id_card_image",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="身份证照片"
            ),
        ),
    ]
