# Generated by Django 4.2.16 on 2026-06-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0005_owner_id_card_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="owner/", verbose_name="头像"
            ),
        ),
    ]
