# Generated by Django 4.2.16 on 2026-06-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0006_owner_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="id_card",
            field=models.CharField(
                db_index=True, max_length=18, unique=True, verbose_name="身份证号"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="phone",
            field=models.CharField(
                db_index=True, max_length=20, unique=True, verbose_name="手机号"
            ),
        ),
    ]
