# Generated by Django 4.2.16 on 2026-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0007_alter_owner_id_card_alter_owner_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
