# Generated by Django 4.2.16 on 2026-06-16 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='会话标题')),
                ('target_role', models.CharField(choices=[('customer_service', '客服人员'), ('finance_staff', '财务人员'), ('repair_staff', '维修员'), ('property_admin', '物业管理员')], default='customer_service', max_length=40, verbose_name='目标角色')),
                ('status', models.CharField(choices=[('active', '沟通中'), ('resolved', '已解决'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='会话状态')),
                ('last_message', models.TextField(blank=True, default='', verbose_name='最后消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('participants', models.ManyToManyField(blank=True, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='参与人')),
            ],
            options={
                'verbose_name': '站内会话',
                'verbose_name_plural': '站内会话',
                'db_table': 'chat_conversation',
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('system', '系统')], default='text', max_length=20, verbose_name='消息类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation', verbose_name='所属会话')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '站内消息',
                'verbose_name_plural': '站内消息',
                'db_table': 'chat_message',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
