# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="end_reason",
            field=models.CharField(
                blank=True,
                choices=[("manual", "人工结束"), ("timeout", "超时结束")],
                max_length=20,
                null=True,
                verbose_name="结束原因",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="rating_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                verbose_name="服务评分",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="rating_comment",
            field=models.TextField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="服务评价",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="rating_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="评分时间"),
        ),
    ]
