# Generated by Codex on 2026-06-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation_timeout_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("owner", "业主"),
                    ("customer_service", "客服人员"),
                    ("finance_staff", "财务人员"),
                    ("repair_staff", "维修员"),
                    ("property_admin", "物业管理员"),
                ],
                default="customer_service",
                max_length=40,
                verbose_name="目标角色",
            ),
        ),
    ]
